# Generated by Django 5.0.6 on 2024-07-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_product_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(blank=True, upload_to="photos/products"),
        ),
    ]
