# Generated by Django 5.0.6 on 2024-07-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_number",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
