# Generated by Django 5.0.6 on 2024-07-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_product_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
