# Generated by Django 5.0.6 on 2024-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cart_user_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.IntegerField(default=1),
        ),
    ]
