# Generated by Django 5.0.6 on 2024-07-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cart_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
    ]
