# Generated by Django 5.0.6 on 2024-07-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_company_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="company_number",
        ),
    ]
