# Generated by Django 5.0.6 on 2024-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_company_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company_number",
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
