# Generated by Django 5.0.6 on 2024-07-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_order_company_number_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="csv_exported",
            field=models.BooleanField(default=False),
        ),
    ]
